version: '3.4'

# This is the TickFlow production Docker Compose spec
# You MUST have a .env file in this dir with the following vars set:
# MARIADB_ROOT_PASSWORD
# MARIADB_USER
# MARIADB_PASSWORD
# MARIADB_DATABASE
# INTERNAL_PORT

services:
  tickflow:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      # TODO: user perms instead of root
      DATABASE_URL: "mysql://root:${MARIADB_ROOT_PASSWORD}@tickflow-db:3306/MARIADB_DATABASE"
    volumes:
      - ./logs:/usr/src/app/logs
      - /var/mail/tickflow:/usr/src/app/mailbox
    ports:
      - "${INTERNAL_PORT}:3000"
    # Ensure db is migrated to current version, generate bindings, and serve
    command: sh -c "sleep 10 && npx prisma migrate dev --name init && npx prisma generate && npm start "
  tickflow-db:
    image: mariadb:11
    volumes:
      - ./db-backup:/backup
      - ./data:/var/lib/mysql
    env_file:
      - .env
