version: '3.4'

services:
  tickflow:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://root:p@ssw0rd@tickflow-db:3306/tickflow_db"
    volumes:
      - ./logs:/usr/src/app/logs
      - /var/mail/tickflow:/usr/src/app/mailbox
    ports:
      - 3000:3000
    command: sh -c "sleep 10 && npx prisma migrate dev --name init && npx prisma generate && npm start "
  tickflow-db:
    image: mariadb:11
    #volumes:
      #- ./mock_sql:/docker-entrypoint-initdb.d
    #ports:
      #- 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=p@ssw0rd
      - MARIADB_USER=user
      - MARIADB_PASSWORD=p@ssw0rd
      - MARIADB_DATABASE=tickflow_db
